#!/bin/sh


# ==========================================================================
# Basic ticket information functions
# --------------------------------------------------------------------------

_ticket_name()
{
    echo "ticket/${1}"
}

_ticket_number()
{
    git branch 2>/dev/null \
        | grep -e '^* ticket' \
        | sed -e 's/* ticket[\/-]\([0-9]\{1,\}\)/\1/'
}

_current_branch()
{
    git branch 2>/dev/null \
        | grep -e '^* ' \
        | sed -e 's/* \(.*\)/\1/'
}

_branch_exists()
{
    `git show-ref --verify --quiet refs/heads/"$1"` \
        && echo !$?
}

_remote_branch_exists()
{
    `git show-ref --verify --quiet remotes/origin/"$1"` \
        && echo !$?
}

# ==========================================================================
# Git macros
# --------------------------------------------------------------------------

_git_delete_branch()
{
    branch=$1
    test -z $branch && echo "branch required." 1>&2 && exit 1
    if [ $(_branch_exists $branch) ]; then
        git branch -d $branch
    else
        echo "No local branch '$branch' to delete." 1>&2 && exit 1
    fi
    if [ $(_remote_branch_exists $branch) ]; then
        git branch -d -r origin/$branch
        git push origin :refs/heads/$branch
    else
        echo "No remote branch of ${branch}." 1>&2 && exit 1
    fi
    exit 0
}

_git_count_incoming()
{
    branch=$1
    current=$(_current_branch)
    git log --pretty=%p "$branch" "^$current" | wc -l
}

# ==========================================================================
# The Subcommands
# --------------------------------------------------------------------------


usage()
{
	echo "usage: git ticket <number|subcommand>"
	echo
	echo "Available subcommands are:"
    echo "   number  Get the number of the current ticket."
	echo "   list    Show all of your ticket/#... branches."
	echo "   open    Create or switch to a ticket branch."
	echo "   browse  Launch the Redmine page for current ticket in whatever browser git uses."
	echo "   status  Show information about a ticket from Redmine."
	echo "   stage*  Merge a ticket's changes into current branch."
	echo "   close*  Merge and delete specified ticket's branches."
	echo
}


main()
 {
	if [ $# -lt 1 ]; then
		usage
		exit 1
	fi

    case "$1" in

        number|no)
            ticket=$(_ticket_number)
            branch=$(_current_branch)
            test -z "$ticket" && exit 1
            # && echo "'$branch' is not a ticket branch." 1>&2
            echo "$ticket"
            exit $?
            ;;

        list)
            shift;
            git branch "$@" | grep -e 'ticket[/-]#\?[0-9]\+'
            ;;

        view|browse|update|status|subject|edit)
            git-redmine "$@"
            exit $?
            ;;

        stage)
            shift;
            test -z $1 \
                && echo "ticket <number> required." 1>&2 \
                && exit 1

            number="$1"; shift
            subject=$(git-redmine subject "$number")
            percent=$(echo "${1:-100}" | sed -e 's/\([0-9]\{1,\}\)$/\1%/')
            branch=$(_ticket_name "$number")

            if [ $(_git_count_incoming $branch) -gt 1 ]; then
                git merge --no-ff $branch -e -m"[#${number}] ${subject} (Staged ${percent})"
            else
                git merge $branch
            fi
            exit 0
            ;;

        close)
            shift;
            test -z $1 \
                && echo "ticket <number> required." 1>&2 \
                && exit 1
            number="$1"; shift
            subject=$(git-redmine subject "$number")
            branch=$(_ticket_name "$number")
            percent=$(echo "${1:-100}" | sed -e 's/\([0-9]\{1,\}\)$/\1%/')

            if [ $(_git_count_incoming $branch) -gt 1 ]; then
                git merge --no-ff $branch -e -m"[#${number}] ${subject} (Closed ${percent})" \
                    && _git_delete_branch $branch
            else
                git merge $branch && _git_delete_branch $branch
            fi
            exit 0
            ;;

        not-in)
            shift
            other="${1:-dev-master}"
            current=$(_current_branch)
            git log "$(_current_branch)" "^$other"
            ;;

        delete|del)
            test -z $2 \
                && echo "ticket <number> required." 1>&2 \
                && exit 1
            branch=$(_ticket_name $2)
            _git_delete_branch $branch
            # echo "You're gonna have to pull the trigger yourself:"
            # echo git branch -D $branch
            ;;

        create)
            echo "Ticket creation is not supported." 1>&2 \
                && exit 1
            #_curl_redmine_create "${@:2}"
            ;;

        *|open|start|switch)
            case "$1" in
                ("start"|"open"|"switch") shift;;
            esac

            if [ ! -z "${1##*[!0-9]*}" ]; then
                branch=$(_ticket_name $1)
            else
                echo "ticket <number> required." && exit 1
            fi

            if [ ! $(_branch_exists $branch) ]; then
                git checkout -b $branch &> /dev/null
            else
                git checkout $branch &> /dev/null
            fi
            exit $?
            ;;
    esac

    exit $?
}

main "$@"
